### ISSUE TITLE
note without css selector

### ISSUE THREAD

**Issue by LegendKan** [wspl/creeper#2]
gallery(@page=0) = "https://e-hentai.org/g/1034547/27cc8cb432/?p={@page}"
tags[]: gallery -> $("div#taglist table tr td:eq(1) div a")
      name: .html

The name will always return the first html selected by css("div#taglist table tr td:eq(1) div a").

**Comment by wspl** [comment]
Hi,
Can you describe the problem in more detail?

**Comment by LegendKan** [comment]
I want to get and print all tags from the page https://e-hentai.org/g/1034547/27cc8cb432/ using the following creeper script:
![ed4ae0ae-6857-4a1b-a543-25dac7712912](https://cloud.githubusercontent.com/assets/2472964/23347737/3d302a08-fcdf-11e6-8355-03e51cdde79d.png)

and my main.go prints the tags:

![14d07e0f-8641-465e-853a-5ea19607812e](https://cloud.githubusercontent.com/assets/2472964/23347749/50085858-fcdf-11e6-9225-9d6cbdf3f542.png)

When I run main.go, it always print the first tag(apsnish) in the page:

![8c363fda-bc40-45c6-8b89-09d30d712dd7](https://cloud.githubusercontent.com/assets/2472964/23347762/7785c2ee-fcdf-11e6-813e-adfab69a1855.png)

Maybe my creeper script is wrong, what is the correct one?

**Comment by wspl** [comment]
I just fixed this bug. Now you can try the following code to achieve the same purpose
```go
c := creeper.New(`
gallery(@page=0) = "https://e-hentai.org/g/1034547/27cc8cb432/?p={@page}"
tags[]: gallery -> $("div#taglist table tr td div a")
	name*: .html`)
c.Array("tags").Each(func(c *creeper.Creeper) {
	println(c.String("name"))
})
```
Tip: The `*` after the field name indicates that this is a primary key for deduplication and judging the terminating page.

Thanks for reporting.
